### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#44]
The admin dashboard should contain the following:

- [x] List of all schools and TAs
- [x] Functionality to create a new school + approved domain #45 
- [ ] Functionality to edit, update or delete a school
- [x] Link to aggregated data analysis
- [x] Add admin authentication

**Comment by jackcarlisle** [comment]
Re-opening with #129
